# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: It Ain't Easy Being Cheesy
description: Random thoughts by Chike Orjih.
paginate: 5

# Build settings
markdown: kramdown

# gems
plugins: [jekyll-paginate, jekyll-admin]

# other
array: []
host_url: http://blog.chikeorjih.com
